name: Deploy_symfony_react
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deyploing

    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - uses: actions/checkout@v2

      - name: APT UPDATE and INSTALL SSHPASS
        run: sudo apt update && sudo apt install sshpass

      - name: node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: rm -f package-lock.json
      - run: npm install

      - run: npm run build

      - name: deploys to server
        run:
          sshpass -e ssh -o stricthostkeychecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }}
          "cd public_html/ &&
          git pull &&
          composer install &&
          php bin/console doctrine:migrations:migrate"
