name: Deploy_symfony_react
on:
  push:
    branches: [main]

jobs:
  build-js-production:
    runs-on: ubuntu-latest
    name: Js-to-production

    steps:
      - uses: actions/checkout@v2

      - name: NPM Build
        run: |
          npm install
          npm run build

  deploy:
    runs-on: ubuntu-latest
    name: Deyploing

    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - uses: actions/checkout@v2

      - name: APT UPDATE and INSTALL SSHPASS
        run: sudo apt update && sudo apt install sshpass

      - name: deploys to server
        run:
          sshpass -e ssh -o stricthostkeychecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }}
          "cd public_html/ &&
          git pull https://github.com/P3drodeSousa/testdeployactions.git main &&
          composer install &&
          php bin/console doctrine:migrations:migrate"
